# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ccc426fc1888579b697469d92f85150f2643872959fee2d96b96d1a409a7e43776450b741c8d615447f7c68fc90f718adc4c55ea47861ec813c8319e40c4211

test:
  secret_key_base: 53b991d75bbf56f123df2172f9cdb70bf59f2affb16793e344163a040806d53b3248b69d3bf2db37bd0d06b75fd30d4f72e36c43fba84279cb7f82e7b9804545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
